#%RAML 0.8
title: Inventory API
version: v3.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: "Inventory API"
    content: <b>API for interacting with an inventory of physical resources</b>

schemas:
 - compositeItem.json: !include schema/compositeItem.json
 - compositeItems: !include schema/compositeItems.json
 - item.json: !include schema/item.json
 - materialType.json: !include schema/materialType.json
 - loanType.json: !include schema/loanType.json
 - instance.json: !include schema/instance.json
 - instances: !include schema/instances.json
 - context: !include schema/instance_context.json
 - ingest-status: !include schema/ingest_status.json

traits:
 - secured: !include ../raml-util/traits/auth.raml
 - language: !include ../raml-util/traits/language.raml
 - pageable: !include ../raml-util/traits/pageable.raml
 - searchable: !include ../raml-util/traits/searchable.raml

resourceTypes:
 - collection: !include ../raml-util/rtypes/collection.raml
 - collection-item: !include ../raml-util/rtypes/item-collection.raml

/inventory:
  /items:
    displayName: Items
    type:
      collection:
        exampleCollection: !include examples/composite_items_get.json
        schemaCollection: compositeItems
        schemaItem: compositeItem.json
        exampleItem: !include examples/composite_item_get.json
    get:
      is: [pageable,
          searchable: {description: "by title (using CQL)",
                       example: "title=\"*uproot*\""}]
      responses:
        501:
          description: "Not implemented yet"
    post:
      responses:
        501:
          description: "Not implemented yet"
    delete:
      responses:
        204:
          description: "All items deleted"
        501:
          description: "Not implemented yet"
    /{itemId}:
      type:
        collection-item:
          exampleItem: !include examples/composite_item_get.json
          schema: compositeItem.json
      get:
        responses:
          501:
            description: "Not implemented yet"
      put:
        responses:
          501:
            description: "Not implemented yet"
      delete:
        responses:
          501:
            description: "Not implemented yet"
  /instances:
    displayName: Instances
    type:
      collection:
        exampleCollection: !include  examples/instances_get.json
        schemaCollection: instances
        schemaItem: instance.json
        exampleItem: !include examples/instance_get.json
    get:
      is: [pageable,
          searchable: {description: "by title (using CQL)",
                       example: "title=\"*uproot*\""}]
      responses:
        501:
          description: "Not implemented yet"
    post:
      responses:
        501:
          description: "Not implemented yet"
    delete:
      responses:
        204:
          description: "All instances deleted"
        501:
          description: "Not implemented yet"
    /{instanceId}:
      type:
        collection-item:
          exampleItem: !include examples/instance_get.json
          schema: instance.json
      get:
        responses:
          501:
            description: "Not implemented yet"
      put:
        responses:
          501:
            description: "Not implemented yet"
      delete:
        responses:
          501:
            description: "Not implemented yet"
    /context:
      get:
        description: "Provides Dublin Core context for instances"
        responses:
          200:
            description: "Dublin Core context for instances"
            body:
              application/json:
                example: !include examples/instance_context_get.json
                schema: context
          501:
            description: "Not implemented yet"
  /ingest:
    /mods:
      post:
        body:
          multipart/form-data:
            formParameters:
              file:
                description: MODS file containing items to ingest
                required: true
                type: file
        responses:
          202:
            headers:
              location:
                description: URI pointing to the location of ingest status
          400:
            body:
              text/plain:
                example: "Cannot parse multiple files in a single request"
          500:
            body:
              text/plain:
          501:
            description: "Not implemented yet"
      /status:
        /{id}:
          get:
            description: Status of a MODS ingest
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/ingest_status_get.json
                    schema: ingest-status
              500:
                body:
                  text/plain:
              501:
                description: "Not implemented yet"
